export const ROLES = {
  ADMINISTRADOR: "ADMINISTRADOR",
  ENCARGADO: "ENCARGADO",
  VENDEDOR: "VENDEDOR",
} as const;

export type RolNombre = (typeof ROLES)[keyof typeof ROLES];

// Matriz de permisos por acción. Punto único de verdad: el authGuard del
// backend y los guards de UI del frontend consultan esta misma tabla, así
// nunca hay reglas de permisos duplicadas o desincronizadas entre capas.
export const PERMISOS = {
  PRODUCTOS_ESCRIBIR: [ROLES.ADMINISTRADOR, ROLES.ENCARGADO],
  PRODUCTOS_LEER: [ROLES.ADMINISTRADOR, ROLES.ENCARGADO, ROLES.VENDEDOR],
  STOCK_LEER: [ROLES.ADMINISTRADOR, ROLES.ENCARGADO, ROLES.VENDEDOR],
  STOCK_AJUSTAR: [ROLES.ADMINISTRADOR, ROLES.ENCARGADO],
  CAJA_ABRIR_CERRAR: [ROLES.ADMINISTRADOR, ROLES.ENCARGADO, ROLES.VENDEDOR],
  VENTAS_CREAR: [ROLES.ADMINISTRADOR, ROLES.ENCARGADO, ROLES.VENDEDOR],
  VENTAS_ANULAR: [ROLES.ADMINISTRADOR, ROLES.ENCARGADO],
  DEVOLUCIONES_CREAR: [ROLES.ADMINISTRADOR, ROLES.ENCARGADO],
  CLIENTES_LEER: [ROLES.ADMINISTRADOR, ROLES.ENCARGADO, ROLES.VENDEDOR],
  CLIENTES_ESCRIBIR: [ROLES.ADMINISTRADOR, ROLES.ENCARGADO, ROLES.VENDEDOR],
  CLIENTES_CUENTA_CORRIENTE: [ROLES.ADMINISTRADOR, ROLES.ENCARGADO],
  COMPRAS_LEER: [ROLES.ADMINISTRADOR, ROLES.ENCARGADO],
  COMPRAS_GESTIONAR: [ROLES.ADMINISTRADOR, ROLES.ENCARGADO],
  REPORTES_VER: [ROLES.ADMINISTRADOR, ROLES.ENCARGADO],
  USUARIOS_ADMINISTRAR: [ROLES.ADMINISTRADOR],
} as const satisfies Record<string, readonly RolNombre[]>;

export type Permiso = keyof typeof PERMISOS;

export function tienePermiso(rol: RolNombre, permiso: Permiso): boolean {
  return (PERMISOS[permiso] as readonly RolNombre[]).includes(rol);
}
